<?php namespace ProcessWire;

/**
 * Collects input for InputfieldGeocoder fields
 * @method string ajaxurl()
 */

class InputfieldGeocoder extends InputfieldWrapper {

	public static function getModuleInfo() {
		return array(
			'title' => 'Geocoder',
			'version' => 100,
			'summary' => 'Inputfield for FieldtypeGeocoder.',
			'href' => 'https://github.com/neuerituale/FieldtypeGeocoder',
			'icon' => 'globe',
			'requires' => 'FieldtypeGeocoder',
		);
	}

	public function __construct() {
		parent::__construct();
		$this->label = 'Geocoder';
	}

	/**
	 * Render inputfield
	 * @return string
	 * @throws WireException
	 */
	public function ___render() {


		// Get value and set defaults
		/** @var Geocoder $geocoder */
		$geocoder = $this->attr('value');
		$this->attr('value', '');

		if(!($geocoder instanceof Geocoder)) $geocoder = new Geocoder();
		if(is_null($this->get('hasFieldtype'))) $this->set('hasFieldtype', $this->modules->get('FieldtypeGeocoder'));

		// Add scripts and styles
		/** @var FieldtypeGeocoder $fieldtype */
		$fieldtype = $this->get('hasFieldtype');
		if($fieldtype instanceof FieldtypeGeocoder) {

			if($fieldtype->loadLeafletCss) $this->config->styles->add($fieldtype->libCss);
			if($fieldtype->loadLeafletScript) $this->config->scripts->add($fieldtype->libScript);

			$this->config->styles->add($fieldtype->css ? $this->sanitizePath($fieldtype->css) : $this->config->urls->InputfieldGeocoder . "assets/InputfieldGeocoder.css");
			$this->config->scripts->add($fieldtype->script ? $this->sanitizePath($fieldtype->script) : $this->config->urls->InputfieldGeocoder . "assets/InputfieldGeocoder.js");
		}

		// Add Subfields
		$this->add([
			'type' => 'text',
			'name' => 'geocoderQuery',
			'themeBorder' => 'none',
			'class' => 'InputfieldGeocoderAutocomplete',
			'value' => $geocoder->query,
			'useLanguages' => false,
			'skipLabel' => Inputfield::skipLabelMarkup,
			'collapsed' => Inputfield::collapsedNever,
			'prependMarkup' => "<span class='InputfieldGeocoderAutocompleteStatus'><i class='fa fa-fw fa-angle-double-right'></i></span> <button type='button' class='InputfieldGeocoderAutocompleteClear'><i class='fa fa-fw fa-trash'></i></button>",
			'appendMarkup' => "<span class='InputfieldGeocoderLatlng'></span>"
		]);

		$this->add([
			'type' => 'hidden',
			'name' => 'geocoderFormatted',
			'value' => $geocoder->formatted
		]);

		$this->add([
			'type' => 'hidden',
			'name' => 'geocoderProvider',
			'value' => $geocoder->provider
		]);

		$this->add([
			'type' => 'hidden',
			'name' => 'geocoderStatus',
			'value' => $geocoder->status
		]);

		$this->add([
			'type' => 'hidden',
			'name' => 'geocoderLat',
			'value' => is_numeric($geocoder->lat) ? json_encode($geocoder->lat) : ''
		]);

		$this->add([
			'type' => 'hidden',
			'name' => 'geocoderLng',
			'value' => is_numeric($geocoder->lng) ? json_encode($geocoder->lng) : ''
		]);

		$this->add([
			'type' => 'hidden',
			'name' => 'geocoderGeojson',
			'value' => $geocoder->geodata ? json_encode($geocoder->geodata) : '{}'
		]);

		// Add notes or preview and set initial description value
		$this->appendMarkup("<div class='InputfieldGeocoderPreview'></div>");
		$queryField = $this->get('geocoderQuery');
		if($geocoder->hasStatus(Geocoder::statusNotFound)) $queryField->description = '*' . __('Geoinformation not found') . '*';
		else if(strlen($geocoder->formatted)) $queryField->description = $geocoder->formatted;
		else $queryField->description = '*' . __('Start typing address for searching ...') . '*';

		// default center
		// ?? suppress errors in php 7
		$defaultCenter = [
			$this->hasField->center['lat'] ?? 0,
			$this->hasField->center['lng'] ?? 0
		];

		// Set additional settings
		$this->wrapAttr('data-ajaxurl', $this->ajaxurl());
		$this->wrapAttr('data-defaultcenter', json_encode($defaultCenter));
		$this->wrapAttr('data-notfound', __('Geoinformation not found'));
		$this->wrapAttr('data-apply', __('Apply'));

		// Render
		return parent::___render();
	}

	/**
	 * Process input
	 * @param WireInputData $input
	 * @return InputfieldGeocoder|void
	 */
	public function ___processInput(WireInputData $input) {

		/** @var Geocoder $geocoder */
		$geocoder = $this->attr('value');

		if(!($geocoder instanceof Geocoder)) {
			$geocoder = new Geocoder();
			$this->attr('value', $geocoder);
		}

		$geocoder->setArray([
			'status' => $input->int('geocoderStatus'),
			'formatted' => $input->text('geocoderFormatted'),
			'query' => $input->text('geocoderQuery'),
			'geodata' => json_decode($input->get('geocoderGeojson'), JSON_OBJECT_AS_ARRAY),
			'lat' => $input->get('geocoderLat'), // will be sanitized in setter method
			'lng' => $input->get('geocoderLng'), // will be sanitized in setter method
			'provider' => $input->text('geocoderProvider')
		]);

		// propagate change to field
		if($geocoder->isChanged()) $this->trackChange('value');

		return $this;

	}

	/**
	 * @param $path
	 * @return mixed
	 * @throws WireException
	 */
	public function sanitizePath($path) {
		if(strpos($path, '//') === false) $path = $this->config->urls->root . ltrim($path, '/');
		return $this->wire('sanitizer')->entities($path);
	}

	/**
	 * Get the ajax url (hookable)
	 * @return string
	 */
	public function ___ajaxurl() {
		return $this->config->urls->admin . 'page/search/live/';
	}

	/**
	 * Field Config
	 *
	 * @param Field $field
	 * @return InputfieldWrapper
	 * @throws WireException
	 * @throws WirePermissionException
	 */
	public function ___getConfigInputfields() {

		$value = new Geocoder();

		if($this->has('hasField')) {
			$field = $this->get('hasField');
			if($field->has('center')) $value->setArray( $this->get('hasField')->get('center') );
		}

		// defaults
		$inputfields = parent::___getConfigInputfields();

		$inputfields->add([
			'type' => 'geocoder',
			'name' => 'center',
			'label' => __('Default center'),
			'value' => $value
		]);

		return $inputfields;
	}
}

